Refonte caméra: contrôles avancés, filtres améliorés, égaliseur audio (iOS/Android)
- Ajout des composants  et  (gestes, timers, barres de contrôle, sous-menus, enregistreur)\n- Améliorations des filtres (FFmpeg) et intégration côté \n- Mise à jour de l'égaliseur audio et des modules natifs C++ partagés (Android/iOS)\n- Mises à jour Android (CMakeLists, AudioEQBridge) et iOS (, providers)\n- Nettoyage/remplacement des anciens composants (FilterControls, VideoControl legacy)\n- Mises à jour de configuration: , , , verrous dépendances\n- Ajout du script 🧹 Nettoyage du cache React Native...

Welcome to React Native v0.80
Starting dev server on http://localhost:8081

Error: listen EADDRINUSE: address already in use :::8081
    at Server.setupListenHandle [as _listen2] (node:net:1940:16)
    at listenInCluster (node:net:1997:12)
    at Server.listen (node:net:2102:7)
    at /Users/m1/Desktop/yana/Naaya/node_modules/metro/src/index.flow.js:358:14
    at new Promise (<anonymous>)
    at earlyPortCheck (/Users/m1/Desktop/yana/Naaya/node_modules/metro/src/index.flow.js:354:11)
    at exports.runServer (/Users/m1/Desktop/yana/Naaya/node_modules/metro/src/index.flow.js:128:9)
    at Object.runServer [as func] (/Users/m1/Desktop/yana/Naaya/node_modules/@react-native/community-cli-plugin/dist/commands/start/runServer.js:147:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Command.handleAction (/Users/m1/Desktop/yana/Naaya/node_modules/@react-native-community/cli/build/index.js:139:9)
[VisionCamera] node modules found at /Users/m1/Desktop/yana/Naaya/node_modules/react-native/..
[VisionCamera] react-native-worklets-core not found, Frame Processors disabled!
Found 8 modules for target `Naaya`
link_native_modules! {ios_packages: [{configurations: [], name: "@react-native-async-storage/async-storage", root: "/Users/m1/Desktop/yana/Naaya/node_modules/@react-native-async-storage/async-storage", path: "../node_modules/@react-native-async-storage/async-storage", podspec_path: "/Users/m1/Desktop/yana/Naaya/node_modules/@react-native-async-storage/async-storage/RNCAsyncStorage.podspec", script_phases: []}, {configurations: [], name: "@react-native-community/blur", root: "/Users/m1/Desktop/yana/Naaya/node_modules/@react-native-community/blur", path: "../node_modules/@react-native-community/blur", podspec_path: "/Users/m1/Desktop/yana/Naaya/node_modules/@react-native-community/blur/react-native-blur.podspec", script_phases: []}, {configurations: [], name: "@react-native-community/slider", root: "/Users/m1/Desktop/yana/Naaya/node_modules/@react-native-community/slider", path: "../node_modules/@react-native-community/slider", podspec_path: "/Users/m1/Desktop/yana/Naaya/node_modules/@react-native-community/slider/react-native-slider.podspec", script_phases: []}, {configurations: [], name: "react-native-linear-gradient", root: "/Users/m1/Desktop/yana/Naaya/node_modules/react-native-linear-gradient", path: "../node_modules/react-native-linear-gradient", podspec_path: "/Users/m1/Desktop/yana/Naaya/node_modules/react-native-linear-gradient/BVLinearGradient.podspec", script_phases: []}, {configurations: [], name: "react-native-reanimated", root: "/Users/m1/Desktop/yana/Naaya/node_modules/react-native-reanimated", path: "../node_modules/react-native-reanimated", podspec_path: "/Users/m1/Desktop/yana/Naaya/node_modules/react-native-reanimated/RNReanimated.podspec", script_phases: []}, {configurations: [], name: "react-native-svg", root: "/Users/m1/Desktop/yana/Naaya/node_modules/react-native-svg", path: "../node_modules/react-native-svg", podspec_path: "/Users/m1/Desktop/yana/Naaya/node_modules/react-native-svg/RNSVG.podspec", script_phases: []}, {configurations: [], name: "react-native-video", root: "/Users/m1/Desktop/yana/Naaya/node_modules/react-native-video", path: "../node_modules/react-native-video", podspec_path: "/Users/m1/Desktop/yana/Naaya/node_modules/react-native-video/react-native-video.podspec", script_phases: []}, {configurations: [], name: "react-native-vision-camera", root: "/Users/m1/Desktop/yana/Naaya/node_modules/react-native-vision-camera", path: "../node_modules/react-native-vision-camera", podspec_path: "/Users/m1/Desktop/yana/Naaya/node_modules/react-native-vision-camera/VisionCamera.podspec", script_phases: []}], ios_project_root_path: "/Users/m1/Desktop/yana/Naaya/ios", react_native_path: "../node_modules/react-native"}
[VisionCamera] node modules found at /Users/m1/Desktop/yana/Naaya/node_modules/react-native/..
[VisionCamera] react-native-worklets-core not found, Frame Processors disabled!
Auto-linking React Native modules for target `Naaya`: BVLinearGradient, RNCAsyncStorage, RNReanimated, RNSVG, VisionCamera, react-native-blur, react-native-slider, and react-native-video
Framework build type is static library
[ReactNativeDependencies] Building from source: true
Configuring the target with the New Architecture
[36m[1m[Codegen][0m Analyzing /Users/m1/Desktop/yana/Naaya/package.json[0m
[36m[1m[Codegen][0m [33mSearching for codegen-enabled libraries in the app.[0m
[36m[1m[Codegen][0m Found Naaya[0m
[36m[1m[Codegen][0m [33mSearching for codegen-enabled libraries in the project dependencies.[0m
[36m[1m[Codegen][0m Found @react-native-async-storage/async-storage[0m
[36m[1m[Codegen][0m Found @react-native-community/blur[0m
[36m[1m[Codegen][0m Found @react-native-community/slider[0m
[36m[1m[Codegen][0m Found react-native[0m
[36m[1m[Codegen][0m Found react-native-reanimated[0m
[36m[1m[Codegen][0m Found react-native-svg[0m
[36m[1m[Codegen][0m [33mSearching for codegen-enabled libraries in react-native.config.js[0m
[36m[1m[Codegen][0m Processing Naaya[0m
[36m[1m[Codegen][0m [33mSearching for podspec in the project dependencies.[0m
[36m[1m[Codegen][0m Processing rnasyncstorage[0m
[36m[1m[Codegen][0m [33mSearching for podspec in the project dependencies.[0m
[36m[1m[Codegen][0m Supported Apple platforms: ios, macos, tvos, visionos for rnasyncstorage[0m
[36m[1m[Codegen][0m Processing rnblurview[0m
[36m[1m[Codegen][0m [33mSearching for podspec in the project dependencies.[0m
[36m[1m[Codegen][0m Supported Apple platforms: ios, tvos, visionos for rnblurview[0m
[36m[1m[Codegen][0m Processing RNCSlider[0m
[36m[1m[Codegen][0m [33mSearching for podspec in the project dependencies.[0m
[36m[1m[Codegen][0m Supported Apple platforms: ios, visionos for RNCSlider[0m
[36m[1m[Codegen][0m Processing FBReactNativeSpec[0m
[36m[1m[Codegen][0m [33mSearching for podspec in the project dependencies.[0m
[36m[1m[Codegen][0m Processing rncore[0m
[36m[1m[Codegen][0m [33mSearching for podspec in the project dependencies.[0m
[36m[1m[Codegen][0m Processing rnreanimated[0m
[36m[1m[Codegen][0m [33mSearching for podspec in the project dependencies.[0m
[36m[1m[Codegen][0m Supported Apple platforms: ios, macos, tvos, visionos for rnreanimated[0m
[36m[1m[Codegen][0m Processing rnsvg[0m
[36m[1m[Codegen][0m [33mSearching for podspec in the project dependencies.[0m
[36m[1m[Codegen][0m Supported Apple platforms: ios, macos, tvos, visionos for rnsvg[0m
[36m[1m[Codegen][0m Generating Native Code for Naaya - ios[0m
[36m[1m[Codegen][0m Generated artifacts: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios[0m
[36m[1m[Codegen][0m Generating Native Code for rnasyncstorage - ios[0m
[36m[1m[Codegen][0m Generated artifacts: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios[0m
[36m[1m[Codegen][0m Generating Native Code for rnblurview - ios[0m
[36m[1m[Codegen][0m Generated artifacts: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios[0m
[36m[1m[Codegen][0m Generating Native Code for RNCSlider - ios[0m
[36m[1m[Codegen][0m Generated artifacts: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios[0m
[36m[1m[Codegen][0m [33m[Codegen - FBReactNativeSpec] Skipping iOS code generation for FBReactNativeSpec as it has been generated already.[0m
[36m[1m[Codegen][0m [33m[Codegen - rncore] Skipping iOS code generation for rncore as it has been generated already.[0m
[36m[1m[Codegen][0m Generating Native Code for rnreanimated - ios[0m
[36m[1m[Codegen][0m Generated artifacts: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios[0m
[36m[1m[Codegen][0m Generating Native Code for rnsvg - ios[0m
[36m[1m[Codegen][0m Generated artifacts: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios[0m
[36m[1m[Codegen][0m Generating RCTThirdPartyComponentsProvider.h[0m
[36m[1m[Codegen][0m Generated artifact: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios/RCTThirdPartyComponentsProvider.h[0m
[36m[1m[Codegen][0m Generating RCTThirdPartyComponentsProvider.mm[0m
[36m[1m[Codegen][0m Generated artifact: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios/RCTThirdPartyComponentsProvider.mm[0m
[36m[1m[Codegen][0m Generating RCTModulesProvider.h[0m
[36m[1m[Codegen][0m Generated artifact: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios/RCTModuleProviders.h[0m
[36m[1m[Codegen][0m Generating RCTModuleProviders.mm[0m
[36m[1m[Codegen][0m Generated artifact: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios/RCTModuleProviders.mm[0m
[36m[1m[Codegen][0m Generating RCTAppDependencyProvider[0m
[36m[1m[Codegen][0m Generated artifact: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios/RCTAppDependencyProvider.h[0m
[36m[1m[Codegen][0m Generated artifact: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios/RCTAppDependencyProvider.mm[0m
[36m[1m[Codegen][0m Generated podspec: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios/ReactAppDependencyProvider.podspec[0m
[36m[1m[Codegen][0m Generated podspec: /Users/m1/Desktop/yana/Naaya/ios/build/generated/ios/ReactCodegen.podspec[0m
[36m[1m[Codegen][0m [33mDone.[0m
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[VisionCamera] node modules found at /Users/m1/Desktop/yana/Naaya/node_modules/react-native/..
[VisionCamera] react-native-worklets-core not found, Frame Processors disabled!
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `fast_float` from `../node_modules/react-native/third-party-podspecs/fast_float.podspec`
Fetching podspec for `fmt` from `../node_modules/react-native/third-party-podspecs/fmt.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.80.2/react-native-artifacts-0.80.2-hermes-ios-debug.tar.gz
Downloading dependencies
Installing BVLinearGradient (2.8.3)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.80.2)
Installing RCT-Folly (2024.11.18.00)
Installing RCTDeprecation (0.80.2)
Installing RCTRequired (0.80.2)
Installing RCTTypeSafety (0.80.2)
Installing RNCAsyncStorage (2.2.0)
Installing RNReanimated (3.19.1)
Installing RNSVG (15.12.1)
Installing React (0.80.2)
Installing React-Core (0.80.2)
Installing React-CoreModules (0.80.2)
Installing React-Fabric (0.80.2)
Installing React-FabricComponents (0.80.2)
Installing React-FabricImage (0.80.2)
Installing React-ImageManager (0.80.2)
Installing React-Mapbuffer (0.80.2)
Installing React-NativeModulesApple (0.80.2)
Installing React-RCTActionSheet (0.80.2)
Installing React-RCTAnimation (0.80.2)
Installing React-RCTAppDelegate (0.80.2)
Installing React-RCTBlob (0.80.2)
Installing React-RCTFBReactNativeSpec (0.80.2)
Installing React-RCTFabric (0.80.2)
Installing React-RCTImage (0.80.2)
Installing React-RCTLinking (0.80.2)
Installing React-RCTNetwork (0.80.2)
Installing React-RCTRuntime (0.80.2)
Installing React-RCTSettings (0.80.2)
Installing React-RCTText (0.80.2)
Installing React-RCTVibration (0.80.2)
Installing React-RuntimeApple (0.80.2)
Installing React-RuntimeCore (0.80.2)
Installing React-RuntimeHermes (0.80.2)
Installing React-callinvoker (0.80.2)
Installing React-cxxreact (0.80.2)
Installing React-debug (0.80.2)
Installing React-defaultsnativemodule (0.80.2)
Installing React-domnativemodule (0.80.2)
Installing React-featureflags (0.80.2)
Installing React-featureflagsnativemodule (0.80.2)
Installing React-graphics (0.80.2)
Installing React-hermes (0.80.2)
Installing React-idlecallbacksnativemodule (0.80.2)
Installing React-jserrorhandler (0.80.2)
Installing React-jsi (0.80.2)
Installing React-jsiexecutor (0.80.2)
Installing React-jsinspector (0.80.2)
Installing React-jsinspectorcdp (0.80.2)
Installing React-jsinspectornetwork (0.80.2)
Installing React-jsinspectortracing (0.80.2)
Installing React-jsitooling (0.80.2)
Installing React-jsitracing (0.80.2)
Installing React-logger (0.80.2)
Installing React-microtasksnativemodule (0.80.2)
Installing React-oscompat (0.80.2)
Installing React-perflogger (0.80.2)
Installing React-performancetimeline (0.80.2)
Installing React-rendererconsistency (0.80.2)
Installing React-renderercss (0.80.2)
Installing React-rendererdebug (0.80.2)
Installing React-rncore (0.80.2)
Installing React-runtimeexecutor (0.80.2)
Installing React-runtimescheduler (0.80.2)
Installing React-timing (0.80.2)
Installing React-utils (0.80.2)
Installing ReactAppDependencyProvider (0.80.2)
Installing ReactCodegen (0.80.2)
Installing ReactCommon (0.80.2)
Installing SocketRocket (0.7.1)
Installing VisionCamera (3.9.2)
Installing Yoga (0.0.0)
Installing boost (1.84.0)
Installing fast_float (8.0.0)
Installing fmt (11.0.2)
Installing glog (0.3.5)
Installing hermes-engine (0.80.2)
Installing react-native-blur (4.4.1)
Installing react-native-slider (4.5.7)
Installing react-native-video (6.16.1)
Generating Pods project
Setting USE_HERMES build settings
Setting REACT_NATIVE_PATH build settings
Setting SWIFT_ACTIVE_COMPILATION_CONDITIONS build settings
[Ccache]: Removing Ccache from CC, LD, CXX & LDPLUSPLUS build settings
[SPM] Cleaning old SPM dependencies from Pods project
[SPM] Adding SPM dependencies to Pods project
[Privacy Manifest Aggregation] Appending aggregated reasons to existing PrivacyInfo.xcprivacy file.
[Privacy Manifest Aggregation] Reading .xcprivacy files to aggregate all used Required Reason APIs.
Setting CLANG_CXX_LANGUAGE_STANDARD to c++20 on /Users/m1/Desktop/yana/Naaya/ios/Naaya.xcodeproj

==================== DEPRECATION NOTICE =====================
Calling `pod install` directly is deprecated in React Native
because we are moving away from Cocoapods toward alternative
solutions to build the project.
* If you are using Expo, please run:
`npx expo run:ios`
* If you are using the Community CLI, please run:
`yarn ios`
=============================================================

Pod install took 13 [s] to run
Integrating client project
Pod installation complete! There are 82 dependencies from the Podfile and 81 total pods installed.
✅ Cache nettoyé ! Redémarrage de l'application...
🚀 Prêt pour le redémarrage !
Exécutez : npx react-native run-ios ou npx react-native run-android\n- Mises à jour écran  et composants associés